### ISSUE TITLE
Handle special characters

### ISSUE THREAD

**Issue by cekk** [RedTurtle/collective.editablemenu#10]
If a section (or site title) has a special character (for example an apostrophe), the js can't handle it and we cannot edit menu voices

**Comment by nzambello** [comment]
@cekk @pnicolli is this resolved by a11d94f, which is merged into master by #7?

**Comment by nzambello** [comment]
Verified on a site using Plone 5.1rc2 and using development version on `master`.
I had no issues with special characters in title nor in content using pages or displaying folder contents' titles, in which I put special chars.

So, I'm closing this issue. If any issue comes out, we can re-open it.
