### ISSUE TITLE
Missing multi-rows feature in #4

### ISSUE THREAD

**Issue by nzambello** [RedTurtle/collective.editablemenu#5]
PR #4 works well, but there is no support for a feature previously present: multi-rows labels.
In the "current" version, there is a textarea for the title, so it will be useful to keep it.

I will probably try to implement this enhancing the PR, but I don't know if it needs changes in the "backend" calls.

**Comment by pnicolli** [comment]
Nice catch, I didn't realize it was a textarea before. I would suggest closing this and discussing the problem in the PR, since it's not merged yet we can time to fix this before releasing.

**Comment by nzambello** [comment]
With #8, now we can insert new row character and it has being saved.
We should implement something to render elements handling that "\n"

**Comment by cekk** [comment]
I think that we can close this issue with today's merge, right @nzambello ?
